FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-node:12-bionic-build as build

WORKDIR /usr/src/app

SHELL ["/bin/bash", "-c"]

COPY . /usr/src/app/

RUN install_packages jq
RUN source .envrc && IS_DOCKER=true setup
RUN source .envrc && PUBLIC_URL=/e3db yarn build

FROM balenalib/%%BALENA_MACHINE_NAME%%-ubuntu-node:12-bionic-run

COPY --from=build /usr/src/app /usr/src/app

RUN install_packages jq

WORKDIR /usr/src/app

SHELL ["/bin/bash", "-c"]

ENTRYPOINT source .envrc && yarn start-server